// packages/gui-deprecated/src/components/layout/Header.tsx
import { Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState, useEffect } from "react";

export function Header() {
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    // Check initial theme
    const dark = document.documentElement.classList.contains("dark");
    setIsDark(dark);
  }, []);

  const toggleTheme = () => {
    const newDark = !isDark;
    setIsDark(newDark);
    document.documentElement.classList.toggle("dark", newDark);
    localStorage.setItem("theme", newDark ? "dark" : "light");
  };

  return (
    <header className="flex h-16 items-center justify-between border-b bg-card px-6">
      <div className="flex items-center gap-4">
        <h1 className="text-lg font-semibold">agentctl</h1>
      </div>

      <div className="flex items-center gap-4">
        {/* Theme toggle */}
        <Button variant="ghost" size="icon" onClick={toggleTheme}>
          {isDark ? (
            <Sun className="h-4 w-4" />
          ) : (
            <Moon className="h-4 w-4" />
          )}
        </Button>
      </div>
    </header>
  );
}

// packages/gui-svelte/src/lib/components/layout/Header.svelte
<script lang="ts">
  import { Moon, Sun } from "lucide-svelte";

  let isDark = typeof window !== "undefined" && document.documentElement.classList.contains("dark");

  function toggleTheme() {
    isDark = !isDark;
    if (isDark) {
      document.documentElement.classList.add("dark");
      localStorage.setItem("theme", "dark");
    } else {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("theme", "light");
    }
  }
</script>

<header class="flex h-16 items-center justify-between border-b bg-card px-6">
  <div class="flex items-center gap-4">
    <!-- Workspace selector placeholder -->
    <span class="text-sm text-muted-foreground">Workspace: default</span>
  </div>

  <div class="flex items-center gap-4">
    <!-- Theme toggle -->
    <button
      on:click={toggleTheme}
      class="rounded-md p-2 hover:bg-accent transition-colors"
      title={isDark ? "Switch to light mode" : "Switch to dark mode"}
    >
      {#if isDark}
        <Sun class="h-5 w-5" />
      {:else}
        <Moon class="h-5 w-5" />
      {/if}
    </button>
  </div>
</header>
