// packages/gui/src/components/layout/Layout.tsx
import { Outlet } from "react-router-dom";
import { Sidebar } from "./Sidebar";
import { Header } from "./Header";
import { useSSE } from "@/api/hooks";

export function Layout() {
  // Enable SSE for real-time updates
  useSSE();

  return (
    <div className="flex h-screen bg-background">
      <Sidebar />
      <div className="flex flex-1 flex-col overflow-hidden">
        <Header />
        <main className="flex-1 overflow-auto p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

// packages/gui-svelte/src/lib/components/layout/Layout.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { startSSE } from "@/lib/api/sse";
  import Sidebar from "./Sidebar.svelte";
  import Header from "./Header.svelte";

  let stopSSE: (() => void) | null = null;

  onMount(() => {
    stopSSE = startSSE();
  });

  onDestroy(() => {
    if (stopSSE) {
      stopSSE();
    }
  });
</script>

<div class="flex h-screen bg-background">
  <Sidebar />
  <div class="flex flex-1 flex-col overflow-hidden">
    <Header />
    <main class="flex-1 overflow-auto p-6">
      <slot />
    </main>
  </div>
</div>
