// packages/gui-deprecated/src/pages/BlackboardPage.tsx
import { useState } from "react";
import { useBlackboard } from "@/api/hooks";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { formatRelativeTime, truncate } from "@/lib/utils";
import { RefreshCw, Clipboard, Clock, Lock } from "lucide-react";
import type { BlackboardRecord } from "@/types";

export function BlackboardPage() {
  const [nsFilter, setNsFilter] = useState("");
  const [topicFilter, setTopicFilter] = useState("");
  const [selectedRecord, setSelectedRecord] = useState<BlackboardRecord | null>(null);

  const { data, isLoading, refetch, isFetching } = useBlackboard({
    ns: nsFilter || undefined,
    topic: topicFilter || undefined,
    all: nsFilter === "" && topicFilter === "",
    limit: 100,
  });

  const records = data?.records || [];

  // Format timestamp to readable date
  const formatTimestamp = (ts: number) => {
    if (!ts) return "N/A";
    // ts is Unix seconds
    const date = new Date(ts * 1000);
    return date.toLocaleString();
  };

  // Check if record is expired
  const isExpired = (record: BlackboardRecord) => {
    if (!record.ttl_sec || record.ttl_sec <= 0) return false;
    const expiresAt = record.ts + record.ttl_sec;
    return Date.now() / 1000 > expiresAt;
  };

  // Check if record is leased
  const isLeased = (record: BlackboardRecord) => {
    if (!record.lease_by || !record.lease_exp) return false;
    return Date.now() / 1000 < record.lease_exp;
  };

  // Try to parse payload as JSON for pretty display
  const formatPayload = (payload: string) => {
    try {
      const parsed = JSON.parse(payload);
      return JSON.stringify(parsed, null, 2);
    } catch {
      return payload;
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Blackboard</h1>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          disabled={isFetching}
        >
          <RefreshCw className={`h-4 w-4 mr-2 ${isFetching ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex gap-4">
            <div className="w-48">
              <label className="text-sm font-medium mb-1 block">Namespace</label>
              <Input
                placeholder="Leave empty for all, or: default"
                value={nsFilter}
                onChange={(e) => setNsFilter(e.target.value)}
              />
            </div>
            <div className="w-48">
              <label className="text-sm font-medium mb-1 block">Topic</label>
              <Input
                placeholder="Leave empty for all, or: *"
                value={topicFilter}
                onChange={(e) => setTopicFilter(e.target.value)}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Records */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clipboard className="h-5 w-5" />
            Records ({records.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-8">
              <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : records.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <Clipboard className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No blackboard records found</p>
              <p className="text-sm mt-2">
                The blackboard is used for agent coordination and shared state.
              </p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Topic</TableHead>
                  <TableHead>Namespace</TableHead>
                  <TableHead>Payload</TableHead>
                  <TableHead>TTL</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Created</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {records.map((record) => (
                  <TableRow
                    key={record.id}
                    className="cursor-pointer hover:bg-muted/50"
                    onClick={() => setSelectedRecord(record)}
                  >
                    <TableCell className="font-mono text-sm">
                      {record.topic}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{record.ns}</Badge>
                    </TableCell>
                    <TableCell className="max-w-md">
                      <span className="text-xs text-muted-foreground font-mono">
                        {truncate(record.payload, 80)}
                      </span>
                    </TableCell>
                    <TableCell>
                      {record.ttl_sec > 0 ? (
                        <span className="flex items-center gap-1 text-sm">
                          <Clock className="h-3 w-3" />
                          {record.ttl_sec}s
                        </span>
                      ) : (
                        <span className="text-muted-foreground text-sm">-</span>
                      )}
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        {isExpired(record) && (
                          <Badge variant="destructive">Expired</Badge>
                        )}
                        {isLeased(record) && (
                          <Badge variant="secondary" className="flex items-center gap-1">
                            <Lock className="h-3 w-3" />
                            Leased
                          </Badge>
                        )}
                        {!isExpired(record) && !isLeased(record) && (
                          <Badge variant="default">Active</Badge>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">
                      {formatRelativeTime(new Date(record.ts * 1000).toISOString())}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Record Detail Modal */}
      <Dialog open={!!selectedRecord} onOpenChange={(open) => !open && setSelectedRecord(null)}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Clipboard className="h-5 w-5" />
              {selectedRecord?.topic}
            </DialogTitle>
          </DialogHeader>
          {selectedRecord && (
            <div className="space-y-4">
              {/* Metadata */}
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-muted-foreground">Namespace:</span>
                  <Badge variant="outline" className="ml-2">{selectedRecord.ns}</Badge>
                </div>
                <div>
                  <span className="text-muted-foreground">Topic:</span>
                  <span className="ml-2 font-mono">{selectedRecord.topic}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Created:</span>
                  <span className="ml-2">{formatTimestamp(selectedRecord.ts)}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">TTL:</span>
                  <span className="ml-2">
                    {selectedRecord.ttl_sec > 0 ? `${selectedRecord.ttl_sec} seconds` : "No expiration"}
                  </span>
                </div>
                <div>
                  <span className="text-muted-foreground">Status:</span>
                  <span className="ml-2">
                    {isExpired(selectedRecord) ? (
                      <Badge variant="destructive">Expired</Badge>
                    ) : isLeased(selectedRecord) ? (
                      <Badge variant="secondary">Leased by {selectedRecord.lease_by}</Badge>
                    ) : (
                      <Badge variant="default">Active</Badge>
                    )}
                  </span>
                </div>
                {selectedRecord.cas_ref && (
                  <div>
                    <span className="text-muted-foreground">CAS Ref:</span>
                    <span className="ml-2 font-mono text-xs">{selectedRecord.cas_ref}</span>
                  </div>
                )}
              </div>

              {/* Lease Info */}
              {selectedRecord.lease_by && (
                <div className="border rounded-md p-3 bg-muted/30">
                  <h4 className="text-sm font-medium flex items-center gap-2 mb-2">
                    <Lock className="h-4 w-4" />
                    Lease Information
                  </h4>
                  <div className="grid grid-cols-2 gap-2 text-sm">
                    <div>
                      <span className="text-muted-foreground">Holder:</span>
                      <span className="ml-2 font-mono">{selectedRecord.lease_by}</span>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Expires:</span>
                      <span className="ml-2">
                        {selectedRecord.lease_exp ? formatTimestamp(selectedRecord.lease_exp) : "N/A"}
                      </span>
                    </div>
                  </div>
                </div>
              )}

              {/* Payload */}
              <div className="border-t pt-4">
                <h4 className="text-sm font-medium text-muted-foreground mb-2">Payload</h4>
                <pre className="bg-muted/50 rounded-md p-4 overflow-x-auto text-sm font-mono whitespace-pre-wrap">
                  {formatPayload(selectedRecord.payload) || "(Empty payload)"}
                </pre>
              </div>

              {/* Record ID */}
              <div className="border-t pt-4 text-xs text-muted-foreground">
                <span>ID: </span>
                <span className="font-mono">{selectedRecord.id}</span>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}

// packages/gui-svelte/src/pages/BlackboardPage.svelte
<script lang="ts">
  import { RefreshCw, Clipboard, Clock, Tag, FileJson } from "lucide-svelte";
  import Layout from "@/lib/components/layout/Layout.svelte";
  import { useBlackboard } from "@/lib/api/hooks";
  import {
    Badge,
    Button,
    Card,
    CardContent,
    CardHeader,
    CardTitle,
    Input,
    Select,
    Table,
    TableHeader,
    TableBody,
    TableRow,
    TableHead,
    TableCell,
    CopyButton,
  } from "@/lib/components/ui";

  let nsFilter = "";
  let topicFilter = "";
  let limitStr = "50";

  $: limit = parseInt(limitStr, 10);

  $: blackboardQuery = useBlackboard({
    ns: nsFilter || undefined,
    topic: topicFilter || undefined,
    limit,
  });

  $: records = $blackboardQuery.data?.records || [];

  function handleRefresh() {
    $blackboardQuery.refetch();
  }

  function formatTimestamp(ts: number): string {
    return new Date(ts * 1000).toLocaleString();
  }

  function formatTTL(ttlSec: number): string {
    if (ttlSec <= 0) return "No expiry";
    if (ttlSec < 60) return `${ttlSec}s`;
    if (ttlSec < 3600) return `${Math.floor(ttlSec / 60)}m`;
    if (ttlSec < 86400) return `${Math.floor(ttlSec / 3600)}h`;
    return `${Math.floor(ttlSec / 86400)}d`;
  }

  function truncatePayload(payload: string, maxLen = 100): string {
    if (payload.length <= maxLen) return payload;
    return payload.slice(0, maxLen) + "...";
  }

  function isValidJson(str: string): boolean {
    try {
      JSON.parse(str);
      return true;
    } catch {
      return false;
    }
  }

  function formatJson(str: string): string {
    try {
      return JSON.stringify(JSON.parse(str), null, 2);
    } catch {
      return str;
    }
  }

  let expandedId: string | null = null;

  function toggleExpand(id: string) {
    expandedId = expandedId === id ? null : id;
  }
</script>

<Layout>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-bold">Blackboard</h1>
      <Button
        variant="outline"
        size="sm"
        on:click={handleRefresh}
        disabled={$blackboardQuery.isFetching}
      >
        <RefreshCw class="h-4 w-4 mr-2 {$blackboardQuery.isFetching ? 'animate-spin' : ''}" />
        Refresh
      </Button>
    </div>

    <!-- Filters -->
    <Card>
      <CardContent class="pt-6">
        <div class="flex gap-4 flex-wrap">
          <div class="w-48">
            <label for="ns-filter" class="text-sm font-medium mb-1 block">Namespace</label>
            <Input
              id="ns-filter"
              placeholder="Filter by namespace..."
              bind:value={nsFilter}
            />
          </div>
          <div class="w-48">
            <label for="topic-filter" class="text-sm font-medium mb-1 block">Topic</label>
            <Input
              id="topic-filter"
              placeholder="Filter by topic..."
              bind:value={topicFilter}
            />
          </div>
          <div class="w-32">
            <label for="limit-select" class="text-sm font-medium mb-1 block">Limit</label>
            <Select id="limit-select" bind:value={limitStr}>
              <option value="25">25</option>
              <option value="50">50</option>
              <option value="100">100</option>
              <option value="200">200</option>
            </Select>
          </div>
        </div>
      </CardContent>
    </Card>

    {#if $blackboardQuery.isLoading}
      <div class="flex items-center justify-center py-16">
        <RefreshCw class="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    {:else if records.length === 0}
      <Card>
        <CardContent class="py-16 text-center">
          <Clipboard class="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
          <h3 class="text-lg font-semibold mb-2">No Records Found</h3>
          <p class="text-muted-foreground">
            {nsFilter || topicFilter
              ? "No records match your filters."
              : "The blackboard is empty."}
          </p>
        </CardContent>
      </Card>
    {:else}
      <Card>
        <CardHeader>
          <CardTitle class="flex items-center gap-2">
            <Clipboard class="h-5 w-5" />
            Records ({records.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Namespace</TableHead>
                <TableHead>Topic</TableHead>
                <TableHead>Payload</TableHead>
                <TableHead>TTL</TableHead>
                <TableHead>Timestamp</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {#each records as record (record.id)}
                <TableRow
                  class="cursor-pointer hover:bg-muted/50"
                  on:click={() => toggleExpand(record.id)}
                >
                  <TableCell>
                    <Badge variant="outline">{record.ns}</Badge>
                  </TableCell>
                  <TableCell>
                    <div class="flex items-center gap-1">
                      <Tag class="h-3 w-3 text-muted-foreground" />
                      <span class="text-sm">{record.topic}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div class="flex items-center gap-2">
                      {#if isValidJson(record.payload)}
                        <FileJson class="h-4 w-4 text-blue-500 shrink-0" />
                      {/if}
                      <span class="font-mono text-xs truncate max-w-[200px]">
                        {truncatePayload(record.payload)}
                      </span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div class="flex items-center gap-1">
                      <Clock class="h-3 w-3 text-muted-foreground" />
                      <span class="text-sm">{formatTTL(record.ttl_sec)}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <span class="text-sm text-muted-foreground">
                      {formatTimestamp(record.ts)}
                    </span>
                  </TableCell>
                </TableRow>
                {#if expandedId === record.id}
                  <TableRow>
                    <TableCell colspan={5}>
                      <div class="p-4 bg-muted/50 rounded-md space-y-3">
                        <div class="flex items-center justify-between">
                          <span class="text-sm font-medium">Full Payload</span>
                          <CopyButton text={record.payload} />
                        </div>
                        <pre class="text-xs font-mono bg-zinc-900 text-zinc-100 p-3 rounded overflow-x-auto max-h-64">{isValidJson(record.payload) ? formatJson(record.payload) : record.payload}</pre>
                        <div class="grid grid-cols-2 gap-4 text-sm">
                          <div>
                            <span class="text-muted-foreground">ID:</span>
                            <span class="font-mono ml-2">{record.id}</span>
                          </div>
                          <div>
                            <span class="text-muted-foreground">Namespace:</span>
                            <span class="ml-2">{record.ns}</span>
                          </div>
                          <div>
                            <span class="text-muted-foreground">Topic:</span>
                            <span class="ml-2">{record.topic}</span>
                          </div>
                          <div>
                            <span class="text-muted-foreground">TTL:</span>
                            <span class="ml-2">{record.ttl_sec}s ({formatTTL(record.ttl_sec)})</span>
                          </div>
                        </div>
                      </div>
                    </TableCell>
                  </TableRow>
                {/if}
              {/each}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    {/if}
  </div>
</Layout>
