// packages/gui-deprecated/src/pages/CodemapsPage.tsx
import { useState } from "react";
import { useCodemaps, useCodemap, useWorkspaces } from "@/api/hooks";
import { deleteCodemap } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { WorkspaceFilter } from "@/components/WorkspaceFilter";
import {
  RefreshCw,
  Map,
  Search,
  ChevronLeft,
  ChevronRight,
  Trash2,
  FileCode,
  Hash,
  FolderTree,
  Tag,
  Code,
} from "lucide-react";

export function CodemapsPage() {
  const [page, setPage] = useState(0);
  const [selectedCodemapId, setSelectedCodemapId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState("");

  const limit = 20;

  const { data: workspacesData } = useWorkspaces();
  const currentWorkspace =
    workspacesData?.current ||
    workspacesData?.workspaces?.find((ws) => ws.is_active)?.path ||
    workspacesData?.workspaces?.[0]?.path;

  const { data: codemapsData, isLoading, refetch, isFetching } = useCodemaps({
    limit,
    workspace: currentWorkspace,
  });

  const { data: codemapDetail, isLoading: isLoadingDetail } = useCodemap(
    selectedCodemapId || "",
    currentWorkspace
  );

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return "-";
    const date = new Date(dateStr);
    return date.toLocaleDateString() + " " + date.toLocaleTimeString();
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this codemap?")) return;
    try {
      await deleteCodemap(id);
      refetch();
      if (selectedCodemapId === id) {
        setSelectedCodemapId(null);
      }
    } catch (err) {
      alert("Failed to delete: " + (err as Error).message);
    }
  };

  // Filter codemaps by search query (client-side)
  const filteredCodemaps = codemapsData?.codemaps.filter((cm) => {
    if (!searchQuery.trim()) return true;
    const query = searchQuery.toLowerCase();
    return (
      cm.title.toLowerCase().includes(query) ||
      cm.query.toLowerCase().includes(query) ||
      cm.id.toLowerCase().includes(query)
    );
  }) || [];

  // Pagination (client-side for now)
  const totalCodemaps = filteredCodemaps.length;
  const pagedCodemaps = filteredCodemaps.slice(page * limit, (page + 1) * limit);
  const totalPages = Math.ceil(totalCodemaps / limit);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-16">
        <RefreshCw className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <h1 className="text-2xl font-bold">Codemaps</h1>
          <WorkspaceFilter />
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          disabled={isFetching}
        >
          <RefreshCw className={`h-4 w-4 mr-2 ${isFetching ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      {/* Stats cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Codemaps</CardTitle>
            <Map className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{codemapsData?.codemaps.length || 0}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Files</CardTitle>
            <FileCode className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {codemapsData?.codemaps.reduce((sum, cm) => sum + cm.file_count, 0) || 0}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Symbols</CardTitle>
            <Hash className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {codemapsData?.codemaps.reduce((sum, cm) => sum + cm.symbol_count, 0) || 0}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search */}
      <div className="flex items-center gap-2">
        <Search className="h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Filter codemaps by title or query..."
          value={searchQuery}
          onChange={(e) => {
            setSearchQuery(e.target.value);
            setPage(0);
          }}
          className="max-w-sm"
        />
      </div>

      {/* Codemaps list */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            <span>Codemaps ({totalCodemaps})</span>
            {totalPages > 1 && (
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  disabled={page === 0}
                  onClick={() => setPage((p) => p - 1)}
                >
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <span className="text-sm text-muted-foreground">
                  Page {page + 1} of {totalPages}
                </span>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={page >= totalPages - 1}
                  onClick={() => setPage((p) => p + 1)}
                >
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {pagedCodemaps.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              {searchQuery ? "No codemaps match your filter" : "No codemaps found"}
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Title</TableHead>
                  <TableHead>Query</TableHead>
                  <TableHead>Files</TableHead>
                  <TableHead>Symbols</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pagedCodemaps.map((codemap) => (
                  <TableRow
                    key={codemap.id}
                    className="cursor-pointer hover:bg-muted/50"
                    onClick={() => setSelectedCodemapId(codemap.id)}
                  >
                    <TableCell className="font-medium max-w-xs truncate">
                      {codemap.title}
                    </TableCell>
                    <TableCell className="max-w-sm truncate text-muted-foreground">
                      {codemap.query}
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1">
                        <FileCode className="h-4 w-4 text-muted-foreground" />
                        {codemap.file_count}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1">
                        <Hash className="h-4 w-4 text-muted-foreground" />
                        {codemap.symbol_count}
                      </div>
                    </TableCell>
                    <TableCell className="whitespace-nowrap text-sm">
                      {formatDate(codemap.created_at)}
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedCodemapId(codemap.id);
                          }}
                        >
                          View
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDelete(codemap.id);
                          }}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Codemap detail dialog */}
      <Dialog open={!!selectedCodemapId} onOpenChange={() => setSelectedCodemapId(null)}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Map className="h-5 w-5" />
              {isLoadingDetail ? "Loading..." : codemapDetail?.title || "Codemap"}
            </DialogTitle>
            {codemapDetail && (
              <div className="flex items-center gap-4 text-sm text-muted-foreground">
                <span>{formatDate(codemapDetail.created_at)}</span>
                <Badge variant="outline">
                  <FileCode className="h-3 w-3 mr-1" />
                  {codemapDetail.file_count} files
                </Badge>
                <Badge variant="outline">
                  <Hash className="h-3 w-3 mr-1" />
                  {codemapDetail.symbol_count} symbols
                </Badge>
              </div>
            )}
          </DialogHeader>

          {isLoadingDetail ? (
            <div className="flex items-center justify-center py-8">
              <RefreshCw className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          ) : codemapDetail ? (
            <div className="flex-1 overflow-y-auto space-y-4 pr-2">
              {/* Description */}
              <Card>
                <CardHeader className="py-3">
                  <CardTitle className="text-sm">Description</CardTitle>
                </CardHeader>
                <CardContent className="py-2">
                  <p className="text-sm">{codemapDetail.description}</p>
                </CardContent>
              </Card>

              {/* Query */}
              <Card>
                <CardHeader className="py-3">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Search className="h-4 w-4" />
                    Query
                  </CardTitle>
                </CardHeader>
                <CardContent className="py-2">
                  <p className="text-sm font-mono bg-muted px-3 py-2 rounded">
                    {codemapDetail.query}
                  </p>
                </CardContent>
              </Card>

              {/* Traces */}
              <Card>
                <CardHeader className="py-3">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <FolderTree className="h-4 w-4" />
                    Traces ({codemapDetail.traces?.length || 0})
                  </CardTitle>
                </CardHeader>
                <CardContent className="py-2">
                  {codemapDetail.traces?.length ? (
                    <Accordion type="multiple" className="w-full">
                      {codemapDetail.traces.map((trace, idx) => (
                        <AccordionItem key={idx} value={`trace-${idx}`}>
                          <AccordionTrigger className="text-sm">
                            <div className="flex items-center gap-3">
                              <Badge variant="outline">#{trace.number}</Badge>
                              <span className="font-medium">{trace.title}</span>
                            </div>
                          </AccordionTrigger>
                          <AccordionContent className="space-y-3">
                            {/* Summary */}
                            <div>
                              <p className="text-sm text-muted-foreground mb-2">
                                {trace.summary}
                              </p>
                            </div>

                            {/* Tree */}
                            {trace.tree && (
                              <div>
                                <h5 className="text-xs font-medium text-muted-foreground mb-1 flex items-center gap-1">
                                  <Code className="h-3 w-3" />
                                  File Tree
                                </h5>
                                <pre className="text-xs font-mono bg-muted p-3 rounded overflow-x-auto">
                                  {trace.tree}
                                </pre>
                              </div>
                            )}

                            {/* Annotations */}
                            {trace.annotations?.length > 0 && (
                              <div>
                                <h5 className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1">
                                  <Tag className="h-3 w-3" />
                                  Annotations ({trace.annotations.length})
                                </h5>
                                <div className="space-y-2">
                                  {trace.annotations.map((ann, annIdx) => (
                                    <div
                                      key={annIdx}
                                      className="border rounded p-3 text-sm"
                                    >
                                      <div className="flex items-center gap-2 mb-1">
                                        <Badge variant="secondary" className="text-xs">
                                          {ann.label}
                                        </Badge>
                                        <span className="font-medium">{ann.title}</span>
                                      </div>
                                      <p className="text-muted-foreground text-xs mb-1">
                                        {ann.description}
                                      </p>
                                      <code className="text-xs bg-muted px-2 py-0.5 rounded">
                                        {ann.path}
                                      </code>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            )}
                          </AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>
                  ) : (
                    <p className="text-sm text-muted-foreground">No traces available</p>
                  )}
                </CardContent>
              </Card>

              {/* Metadata */}
              <Card>
                <CardHeader className="py-3">
                  <CardTitle className="text-sm">Metadata</CardTitle>
                </CardHeader>
                <CardContent className="py-2">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="text-muted-foreground">ID:</span>
                      <code className="ml-2 text-xs bg-muted px-2 py-0.5 rounded">
                        {codemapDetail.id}
                      </code>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Workspace:</span>
                      <code className="ml-2 text-xs bg-muted px-2 py-0.5 rounded">
                        {codemapDetail.workspace}
                      </code>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              Codemap not found
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}

// packages/gui-svelte/src/pages/CodemapsPage.svelte
<script lang="ts">
  import {
    RefreshCw,
    Map as MapIcon,
    FileCode,
    Code2,
    ChevronRight,
    ChevronDown,
    Search,
    Folder,
    Tag,
  } from "lucide-svelte";
  import Layout from "@/lib/components/layout/Layout.svelte";
  import { useCodemaps, useCodemap, useWorkspaces } from "@/lib/api/hooks";
  import {
    Badge,
    Button,
    Card,
    CardContent,
    CardHeader,
    CardTitle,
    Input,
    CopyButton,
    Select,
  } from "@/lib/components/ui";

  let searchQuery = "";
  let selectedId = "";
  let expandedTraces: Set<number> = new Set();
  let selectedWorkspace = "";
  let lastWorkspace = "";

  const workspacesQuery = useWorkspaces();

  $: workspaces = $workspacesQuery.data?.workspaces || [];
  $: defaultWorkspace = resolveWorkspace($workspacesQuery.data?.current, workspaces);

  $: if (!selectedWorkspace && defaultWorkspace) {
    selectedWorkspace = defaultWorkspace;
  }

  $: if (selectedWorkspace !== lastWorkspace) {
    lastWorkspace = selectedWorkspace;
    selectedId = "";
    expandedTraces = new Set();
  }

  $: codemapsQuery = useCodemaps({ limit: 100, workspace: selectedWorkspace || undefined });

  $: codemaps = $codemapsQuery.data?.codemaps || [];
  $: filteredCodemaps = searchQuery
    ? codemaps.filter(
        (c) =>
          c.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
          c.query.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : codemaps;

  $: codemapDetailQuery = useCodemap(selectedId, selectedWorkspace || undefined);
  $: selectedCodemap = $codemapDetailQuery.data;

  function handleRefresh() {
    $codemapsQuery.refetch();
    if (selectedId) {
      $codemapDetailQuery.refetch();
    }
  }

  function selectCodemap(id: string) {
    selectedId = id;
    expandedTraces = new Set();
  }

  function toggleTrace(traceNum: number) {
    if (expandedTraces.has(traceNum)) {
      expandedTraces.delete(traceNum);
    } else {
      expandedTraces.add(traceNum);
    }
    expandedTraces = new Set(expandedTraces);
  }

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString(undefined, {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  }

  type WorkspaceOption = { path: string; is_active?: boolean };

  function resolveWorkspace(current: string | undefined, list: WorkspaceOption[]): string {
    if (current && list.some((ws) => ws.path === current)) {
      return current;
    }
    return list.find((ws) => ws.is_active)?.path || list[0]?.path || "";
  }

</script>

<Layout>
  <div class="h-[calc(100vh-4rem)] flex">
    <!-- Codemaps list sidebar -->
    <div class="w-80 border-r flex flex-col bg-muted/30">
      <div class="p-4 border-b space-y-3">
        <div class="flex items-center justify-between">
          <h2 class="font-semibold">Codemaps</h2>
          <Button
            variant="ghost"
            size="sm"
            on:click={handleRefresh}
            disabled={$codemapsQuery.isFetching}
          >
            <RefreshCw class="h-4 w-4 {$codemapsQuery.isFetching ? 'animate-spin' : ''}" />
          </Button>
        </div>
        <div class="relative">
          <Search class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Filter codemaps..."
            bind:value={searchQuery}
            class="pl-8 h-9"
          />
        </div>
        <div>
          <Select bind:value={selectedWorkspace} disabled={workspaces.length === 0}>
            {#if workspaces.length === 0}
              <option value="">No workspaces found</option>
            {:else}
              {#each workspaces as ws (ws.path)}
                <option value={ws.path}>{ws.name}</option>
              {/each}
            {/if}
          </Select>
        </div>
      </div>

      <div class="flex-1 overflow-y-auto p-2 space-y-1">
        {#if $codemapsQuery.isLoading}
          <div class="flex items-center justify-center py-8">
            <RefreshCw class="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        {:else if filteredCodemaps.length === 0}
          <div class="text-center py-8 text-muted-foreground text-sm">
            {searchQuery ? "No matching codemaps" : "No codemaps found"}
          </div>
        {:else}
          {#each filteredCodemaps as codemap (codemap.id)}
            <button
              type="button"
              class="w-full p-3 rounded-md text-left hover:bg-muted transition-colors {selectedId === codemap.id ? 'bg-muted border border-primary/50' : ''}"
              on:click={() => selectCodemap(codemap.id)}
            >
              <div class="flex items-start gap-2">
                <MapIcon class="h-4 w-4 mt-0.5 shrink-0 text-primary" />
                <div class="flex-1 min-w-0">
                  <p class="font-medium text-sm truncate">{codemap.title}</p>
                  <p class="text-xs text-muted-foreground truncate mt-0.5">
                    {codemap.query}
                  </p>
                  <div class="flex items-center gap-2 mt-2">
                    <Badge variant="secondary" class="text-xs gap-1">
                      <FileCode class="h-3 w-3" />
                      {codemap.file_count} files
                    </Badge>
                    <Badge variant="outline" class="text-xs gap-1">
                      <Code2 class="h-3 w-3" />
                      {codemap.symbol_count} symbols
                    </Badge>
                  </div>
                </div>
              </div>
            </button>
          {/each}
        {/if}
      </div>

      <div class="border-t p-3">
        <p class="text-xs text-muted-foreground">
          {filteredCodemaps.length} codemap{filteredCodemaps.length !== 1 ? "s" : ""}
        </p>
      </div>
    </div>

    <!-- Detail view -->
    <div class="flex-1 overflow-y-auto">
      {#if !selectedId}
        <div class="flex items-center justify-center h-full">
          <div class="text-center">
            <MapIcon class="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
            <h2 class="text-lg font-semibold mb-2">Codemaps</h2>
            <p class="text-muted-foreground">
              Select a codemap to view its traces and annotations
            </p>
          </div>
        </div>
      {:else if $codemapDetailQuery.isLoading}
        <div class="flex items-center justify-center h-full">
          <RefreshCw class="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      {:else if selectedCodemap}
        <div class="p-6 space-y-6">
          <!-- Header -->
          <div>
            <div class="flex items-center gap-2 mb-2">
              <MapIcon class="h-6 w-6 text-primary" />
              <h1 class="text-2xl font-bold">{selectedCodemap.title}</h1>
            </div>
            {#if selectedCodemap.description}
              <p class="text-muted-foreground">{selectedCodemap.description}</p>
            {/if}
          </div>

          <!-- Metadata -->
          <Card>
            <CardContent class="pt-6">
              <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div>
                  <p class="text-sm text-muted-foreground">Query</p>
                  <p class="font-medium">{selectedCodemap.query}</p>
                </div>
                <div>
                  <p class="text-sm text-muted-foreground">Files</p>
                  <p class="font-medium">{selectedCodemap.file_count}</p>
                </div>
                <div>
                  <p class="text-sm text-muted-foreground">Symbols</p>
                  <p class="font-medium">{selectedCodemap.symbol_count}</p>
                </div>
                <div>
                  <p class="text-sm text-muted-foreground">Created</p>
                  <p class="font-medium">{formatDate(selectedCodemap.created_at)}</p>
                </div>
              </div>
              {#if selectedCodemap.workspace}
                <div class="mt-4 pt-4 border-t">
                  <p class="text-sm text-muted-foreground">Workspace</p>
                  <div class="flex items-center gap-2 mt-1">
                    <Folder class="h-4 w-4 text-muted-foreground" />
                    <code class="text-sm font-mono">{selectedCodemap.workspace}</code>
                    <CopyButton text={selectedCodemap.workspace} />
                  </div>
                </div>
              {/if}
            </CardContent>
          </Card>

          <!-- Traces -->
          {#if selectedCodemap.traces && selectedCodemap.traces.length > 0}
            <div class="space-y-4">
              <h2 class="text-lg font-semibold">Traces ({selectedCodemap.traces.length})</h2>

              {#each selectedCodemap.traces as trace (trace.number)}
                <Card>
                  <CardHeader class="cursor-pointer" on:click={() => toggleTrace(trace.number)}>
                    <CardTitle class="flex items-center gap-2 text-base">
                      {#if expandedTraces.has(trace.number)}
                        <ChevronDown class="h-4 w-4" />
                      {:else}
                        <ChevronRight class="h-4 w-4" />
                      {/if}
                      <Badge variant="outline" class="text-xs">#{trace.number}</Badge>
                      {trace.title}
                    </CardTitle>
                  </CardHeader>

                  {#if expandedTraces.has(trace.number)}
                    <CardContent class="space-y-4">
                      {#if trace.summary}
                        <div>
                          <p class="text-sm text-muted-foreground mb-1">Summary</p>
                          <p class="text-sm">{trace.summary}</p>
                        </div>
                      {/if}

                      {#if trace.tree}
                        <div>
                          <p class="text-sm text-muted-foreground mb-1">Tree</p>
                          <pre class="text-xs bg-muted p-3 rounded-md overflow-x-auto font-mono">{trace.tree}</pre>
                        </div>
                      {/if}

                      {#if trace.annotations && trace.annotations.length > 0}
                        <div>
                          <p class="text-sm text-muted-foreground mb-2">
                            Annotations ({trace.annotations.length})
                          </p>
                          <div class="space-y-2">
                            {#each trace.annotations as annotation}
                              <div class="p-3 bg-muted/50 rounded-md">
                                <div class="flex items-center gap-2 mb-1">
                                  <Badge variant="secondary" class="text-xs gap-1">
                                    <Tag class="h-3 w-3" />
                                    {annotation.label}
                                  </Badge>
                                  <span class="font-medium text-sm">{annotation.title}</span>
                                </div>
                                {#if annotation.description}
                                  <p class="text-sm text-muted-foreground mb-2">
                                    {annotation.description}
                                  </p>
                                {/if}
                                {#if annotation.path}
                                  <div class="flex items-center gap-2">
                                    <FileCode class="h-3 w-3 text-muted-foreground" />
                                    <code class="text-xs font-mono text-muted-foreground">
                                      {annotation.path}
                                    </code>
                                    <CopyButton text={annotation.path} />
                                  </div>
                                {/if}
                              </div>
                            {/each}
                          </div>
                        </div>
                      {/if}
                    </CardContent>
                  {/if}
                </Card>
              {/each}
            </div>
          {:else}
            <Card>
              <CardContent class="py-8 text-center text-muted-foreground">
                No traces found for this codemap
              </CardContent>
            </Card>
          {/if}

          <!-- ID footer -->
          <div class="pt-4 border-t">
            <div class="flex items-center gap-2 text-xs text-muted-foreground">
              <span>ID:</span>
              <code class="font-mono">{selectedCodemap.id}</code>
              <CopyButton text={selectedCodemap.id} />
            </div>
          </div>
        </div>
      {/if}
    </div>
  </div>
</Layout>
